spring.application.name=autodrive
server.port=8080

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/autodrive_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

app.tasa-cambio.url=${TASA_CAMBIO_URL:https://open.er-api.com/v6/latest/USD}
app.tasa-cambio.timeout-conexion-ms=3000
app.tasa-cambio.timeout-lectura-ms=5000
app.tasa-cambio.cache-minutos=10
